name: ms-impute-trim
channels:
  - pytorch
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - tqdm
  - scipy
  - scikit-learn
  - pytorch=1.10.*
  - pandas
  - numpy
  - pip
  - pip:
    - flake8==4.0.*
    - pytest==6.2.*
    - unittest2==1.1.* 